'use client';

import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { summarizeBlogPost } from '@/ai/flows/summarize-blog-post';
import { Sparkles, Bot } from 'lucide-react';
import { Skeleton } from './ui/skeleton';

type BlogSummaryProps = {
  postContent: string;
};

export default function BlogSummary({ postContent }: BlogSummaryProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [summary, setSummary] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSummarize = async () => {
    if (summary) {
      setIsOpen(true);
      return;
    }
    setIsOpen(true);
    setIsLoading(true);
    setError('');
    try {
      const result = await summarizeBlogPost({ blogPostContent: postContent });
      setSummary(result.summary);
    } catch (e) {
      console.error(e);
      setError('Sorry, I couldn\'t generate a summary at this time.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button onClick={handleSummarize}>
          <Sparkles className="mr-2 h-4 w-4" />
          AI Summary (TL;DR)
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Bot className="h-5 w-5 text-accent" />
            AI Generated Summary
          </DialogTitle>
          <DialogDescription>
            A quick summary of the blog post, generated by AI.
          </DialogDescription>
        </DialogHeader>
        <div className="py-4">
          {isLoading ? (
            <div className="space-y-2">
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-[75%]" />
            </div>
          ) : error ? (
            <p className="text-destructive">{error}</p>
          ) : (
            <p className="text-sm text-muted-foreground">{summary}</p>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
